### PR TITLE
WIP: add examples for sample masks in README

### PR DESCRIPTION
**Pull request by Hugo-Trentesaux**
add examples for sample masks

(might want to renumber the readme or store the images externally)

### CODE REVIEW

**Comment by Jake-Shadle** [comment]
I cleaned up the README a bit, but could you upload the montage image to [imgur](https://imgur.com/upload) like the rest of the README example outputs? Thanks!

**Comment by Jake-Shadle** [comment]
Uhh sorry I guess I wasn't clear enough, _just_ the montage image, which is used in the README only, but keep the actual input images in the repo so that others can use them locally if they wish.

**Comment by Hugo-Trentesaux** [comment]
Ok, now the example images are stored in the repo and the montage is stored externally. I force pushed it. With the virus, there is a chance I have some more time to work on texture-synthesis :smile:

**Comment by Hugo-Trentesaux** [comment]
Finally you do not want to have examples for sample masks option? Or should I do it differently?

**Comment by Jake-Shadle** [comment]
Oh sorry, we changed the name of our master branch to main and I guess github automatically closed prs, sorry!

**Comment by Hugo-Trentesaux** [comment]
Ok. You mean I could submit a new PR to the "main" branch", right?

**Comment by Jake-Shadle** [comment]
Yes please!

**Pull request closed without merging**
